/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem_rental_mobil_oo_impal;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.UIManager;
import sistem_rental_mobil_oo_impal.panels.ManageMobil;
import sistem_rental_mobil_oo_impal.panels.PermintaanMobil;
import sistem_rental_mobil_oo_impal.panels.Profile;

/**
 *
 * @author Evlive
 */
public class PenyewaInterface extends javax.swing.JFrame {
    Driver driver;
    GridBagLayout layout = new GridBagLayout();
    Profile profile;
    ManageMobil manageMobil;
    PermintaanMobil permintaanMobil;
    
    /**
     * Creates new form Supplier
     */
    public PenyewaInterface() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        this.setLocationRelativeTo(null);
        driver = new Driver();
        
        profile = new Profile();
        DynamicPane.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.fill = GridBagConstraints.BOTH;
        c.gridx = 0;
        c.gridy = 0;
        DynamicPane.add(profile, c);
        
        manageMobil = new ManageMobil();
        c = new GridBagConstraints();
        c.fill = GridBagConstraints.BOTH;
        c.gridx = 0;
        c.gridy = 0;
        DynamicPane.add(manageMobil, c);
        
        permintaanMobil = new PermintaanMobil();
        c = new GridBagConstraints();
        c.fill = GridBagConstraints.BOTH;
        c.gridx = 0;
        c.gridy = 0;
        DynamicPane.add(permintaanMobil, c);
        
        profile.setVisible(true);
        manageMobil.setVisible(false);
        permintaanMobil.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        myProfileButton = new javax.swing.JButton();
        lihatMobilButton = new javax.swing.JButton();
        sewaMobilButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        DynamicPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Evlive.DESKTOP-TSUD57U\\Documents\\NetBeansProjects\\Sistem_Rental_Mobil_OO_Impal\\img\\logo2.png")); // NOI18N

        myProfileButton.setBackground(new java.awt.Color(0, 102, 255));
        myProfileButton.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        myProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        myProfileButton.setText("My Profile");
        myProfileButton.setBorder(null);
        myProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myProfileButtonActionPerformed(evt);
            }
        });

        lihatMobilButton.setBackground(new java.awt.Color(0, 102, 255));
        lihatMobilButton.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lihatMobilButton.setForeground(new java.awt.Color(255, 255, 255));
        lihatMobilButton.setText("Lihat Mobil");
        lihatMobilButton.setBorder(null);
        lihatMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatMobilButtonActionPerformed(evt);
            }
        });

        sewaMobilButton.setBackground(new java.awt.Color(0, 102, 255));
        sewaMobilButton.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        sewaMobilButton.setForeground(new java.awt.Color(255, 255, 255));
        sewaMobilButton.setText("Sewa Mobil");
        sewaMobilButton.setBorder(null);
        sewaMobilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sewaMobilButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(0, 102, 255));
        logoutButton.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.setBorder(null);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Penyewa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lihatMobilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sewaMobilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(myProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lihatMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sewaMobilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        DynamicPane.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DynamicPaneLayout = new javax.swing.GroupLayout(DynamicPane);
        DynamicPane.setLayout(DynamicPaneLayout);
        DynamicPaneLayout.setHorizontalGroup(
            DynamicPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        DynamicPaneLayout.setVerticalGroup(
            DynamicPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DynamicPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DynamicPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileButtonActionPerformed
        profile.setVisible(true);
        manageMobil.setVisible(false);
        permintaanMobil.setVisible(false);
    }//GEN-LAST:event_myProfileButtonActionPerformed

    private void lihatMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatMobilButtonActionPerformed
        profile.setVisible(false);
        manageMobil.setVisible(false);
        permintaanMobil.setVisible(true);
    }//GEN-LAST:event_lihatMobilButtonActionPerformed

    private void sewaMobilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sewaMobilButtonActionPerformed
        profile.setVisible(false);
        manageMobil.setVisible(true);
        permintaanMobil.setVisible(false);
    }//GEN-LAST:event_sewaMobilButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.dispose();
        Login login = new Login();
    }//GEN-LAST:event_logoutButtonActionPerformed

    public Driver getDriver() {
        return driver;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenyewaInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lihatMobilButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton myProfileButton;
    private javax.swing.JButton sewaMobilButton;
    // End of variables declaration//GEN-END:variables
}
