/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem_rental_mobil_oo_impal.panels;

import java.awt.Color;
import sistem_rental_mobil_oo_impal.Driver;

/**
 *
 * @author Evlive
 */
public class LihatLaporanRekening extends javax.swing.JPanel {
    Driver driver;

    /**
     * Creates new form Profile
     */
    public LihatLaporanRekening() {
        initComponents();
        
        this.setBackground(Color.WHITE);
        driver = new Driver();
    }
    
    public void reset() {
        /*emailField.setText("");
        alamatField.setText("");
        contactField.setText("");
        sebagaiField.setText("");*/
    }
    
    public Driver getDriver() {
        return driver;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jumlahField = new javax.swing.JTextField();
        simpanpPadaDatabaseButton = new javax.swing.JButton();
        lihatSemuaLaporanRekeningButton = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel3.setText("Lihat Laporan Rekening");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Jumlah");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Tanggal");

        jumlahField.setEditable(false);
        jumlahField.setBackground(new java.awt.Color(255, 255, 255));
        jumlahField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jumlahField.setBorder(null);

        simpanpPadaDatabaseButton.setBackground(new java.awt.Color(0, 102, 255));
        simpanpPadaDatabaseButton.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        simpanpPadaDatabaseButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanpPadaDatabaseButton.setText("Simpan pada database");
        simpanpPadaDatabaseButton.setBorder(null);
        simpanpPadaDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanpPadaDatabaseButtonActionPerformed(evt);
            }
        });

        lihatSemuaLaporanRekeningButton.setBackground(new java.awt.Color(0, 102, 255));
        lihatSemuaLaporanRekeningButton.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        lihatSemuaLaporanRekeningButton.setForeground(new java.awt.Color(255, 255, 255));
        lihatSemuaLaporanRekeningButton.setText("Lihat semua Laporan Rekening");
        lihatSemuaLaporanRekeningButton.setBorder(null);
        lihatSemuaLaporanRekeningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatSemuaLaporanRekeningButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addGap(2, 2, 2))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jumlahField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(simpanpPadaDatabaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lihatSemuaLaporanRekeningButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel3)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jumlahField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lihatSemuaLaporanRekeningButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(simpanpPadaDatabaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void simpanpPadaDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanpPadaDatabaseButtonActionPerformed
        EditProfile editProfile = new EditProfile();
        editProfile.getDriver().setUserEmail(driver.getUserEmail());
        editProfile.getDriver().setUserNama(driver.getUserNama());
        editProfile.getDriver().setUserAlamat(driver.getUserAlamat());
        editProfile.getDriver().setUserContact(driver.getUserContact());
        editProfile.getDriver().setUserLevel(driver.getUserLevel());
        editProfile.setVisible(true);
    }//GEN-LAST:event_simpanpPadaDatabaseButtonActionPerformed

    private void lihatSemuaLaporanRekeningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatSemuaLaporanRekeningButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lihatSemuaLaporanRekeningButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jumlahField;
    private javax.swing.JButton lihatSemuaLaporanRekeningButton;
    private javax.swing.JButton simpanpPadaDatabaseButton;
    // End of variables declaration//GEN-END:variables
}
