/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem_rental_mobil_oo_impal.panels;

import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import sistem_rental_mobil_oo_impal.Driver;
import sistem_rental_mobil_oo_impal.model.LaporanRekening;

/**
 *
 * @author Evlive
 */
public class LihatLaporanRekening extends javax.swing.JPanel {
    private Driver driver;
    private SimpleDateFormat dateFormat;
    private LaporanRekening laporanRekening;
    
    /**
     * Creates new form Profile
     */
    public LihatLaporanRekening() {
        initComponents();
        
        this.setBackground(Color.WHITE);
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        driver = new Driver();
        laporanRekening = new LaporanRekening();
    }
    
    public String getDate() {
        String date;
        if (tanggal.getDate() == null) {
            date = "";
        } else {
            date = dateFormat.format(tanggal.getDate());
        }
        return date;
    }
    
    public void setDate(String date) {
        tanggal.setDateFormatString(date);
    }
    
    public Driver getDriver() {
        return driver;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lihatSaldoButton = new javax.swing.JButton();
        lihatSemuaLaporanRekeningButton = new javax.swing.JButton();
        tanggal = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel3.setText("Lihat Laporan Rekening");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Tanggal");

        lihatSaldoButton.setBackground(new java.awt.Color(0, 102, 255));
        lihatSaldoButton.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lihatSaldoButton.setForeground(new java.awt.Color(255, 255, 255));
        lihatSaldoButton.setText("Lihat Saldo");
        lihatSaldoButton.setBorder(null);
        lihatSaldoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatSaldoButtonActionPerformed(evt);
            }
        });

        lihatSemuaLaporanRekeningButton.setBackground(new java.awt.Color(0, 102, 255));
        lihatSemuaLaporanRekeningButton.setFont(new java.awt.Font("Century Gothic", 0, 9)); // NOI18N
        lihatSemuaLaporanRekeningButton.setForeground(new java.awt.Color(255, 255, 255));
        lihatSemuaLaporanRekeningButton.setText("Lihat semua Laporan Rekening");
        lihatSemuaLaporanRekeningButton.setBorder(null);
        lihatSemuaLaporanRekeningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatSemuaLaporanRekeningButtonActionPerformed(evt);
            }
        });

        tanggal.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(2, 2, 2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lihatSaldoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lihatSemuaLaporanRekeningButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lihatSaldoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(lihatSemuaLaporanRekeningButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lihatSaldoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatSaldoButtonActionPerformed
        if (tanggal.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Mohon untuk memilih tanggal untuk menampilkan laporan hari ini");
        } else {
            java.util.Date date = tanggal.getDate();
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            int jumlah = driver.getJumlahSaldoLaporanRekening(sqlDate);
            laporanRekening.setJumlah(jumlah);
            laporanRekening.setTanggal(sqlDate);
            LihatSaldo lihatSaldo = new LihatSaldo();
            lihatSaldo.setLaporanRekening(laporanRekening);
            lihatSaldo.setJumlah(jumlah);
            lihatSaldo.setDate(getDate());
            lihatSaldo.setVisible(true);
        }
    }//GEN-LAST:event_lihatSaldoButtonActionPerformed

    private void lihatSemuaLaporanRekeningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatSemuaLaporanRekeningButtonActionPerformed
        LihatSemuaLaporanRekening lihatSemuaLaporanRekening = new LihatSemuaLaporanRekening();
        lihatSemuaLaporanRekening.loadLaporanRekening();
        lihatSemuaLaporanRekening.setVisible(true);
    }//GEN-LAST:event_lihatSemuaLaporanRekeningButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton lihatSaldoButton;
    private javax.swing.JButton lihatSemuaLaporanRekeningButton;
    private com.toedter.calendar.JDateChooser tanggal;
    // End of variables declaration//GEN-END:variables
}
