/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem_rental_mobil_oo_impal.panels;

import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistem_rental_mobil_oo_impal.Driver;
import sistem_rental_mobil_oo_impal.model.Mobil;
import sistem_rental_mobil_oo_impal.model.Penyewa;
import sistem_rental_mobil_oo_impal.model.Supplier;
import sistem_rental_mobil_oo_impal.model.Transaksi;

/**
 *
 * @author Evlive
 */
public class ManageTransaksi extends javax.swing.JPanel {
    private Driver driver;
    private DefaultTableModel model;
    private SimpleDateFormat dateFormat;
    
    /**
     * Creates new form ManageMobil
     */
    public ManageTransaksi() {
        initComponents();
        this.setBackground(Color.WHITE);
        driver  = new Driver();
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        model = (DefaultTableModel) tableTransaksi.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        deleteTransaksiButton = new javax.swing.JButton();
        editTransaksiButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Penyewa", "Nama Mobil", "Jumlah", "Harga", "Tanggal Pengembalian", "Denda", "Status Bayar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTransaksi);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Manage Transaksi");

        deleteTransaksiButton.setBackground(new java.awt.Color(0, 102, 255));
        deleteTransaksiButton.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        deleteTransaksiButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteTransaksiButton.setText("Delete Transaksi");
        deleteTransaksiButton.setBorder(null);
        deleteTransaksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTransaksiButtonActionPerformed(evt);
            }
        });

        editTransaksiButton.setBackground(new java.awt.Color(0, 102, 255));
        editTransaksiButton.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        editTransaksiButton.setForeground(new java.awt.Color(255, 255, 255));
        editTransaksiButton.setText("Edit Transaksi");
        editTransaksiButton.setToolTipText("");
        editTransaksiButton.setBorder(null);
        editTransaksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTransaksiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(deleteTransaksiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editTransaksiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteTransaksiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editTransaksiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteTransaksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTransaksiButtonActionPerformed
        int selectedRow = tableTransaksi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Mohon untuk memilih transaksi yang ingin di delete pada tabel");
        } else {
            Transaksi transaksi = getTransaksi(selectedRow); //ambil transaksi dari database
            Penyewa penyewa = driver.getPenyewaById(transaksi.getIdPenyewa()); //ambil penyewa dari database
            Mobil mobil = driver.getMobilById(transaksi.getIdMobil()); //ambil mobil dari database
            penyewa.setIdTransaksiPenyewa(-1);
            mobil.setJumlah(mobil.getJumlah()+transaksi.getJumlahMobil());
            driver.getDb().updatePenyewa(penyewa.getId(), penyewa);
            driver.getDb().updateMobil(mobil.getId(), mobil);
            driver.getDb().deleteTransaksi(transaksi.getId());
        }
        loadTransaksi(); 
    }//GEN-LAST:event_deleteTransaksiButtonActionPerformed

    private void editTransaksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTransaksiButtonActionPerformed
        EditTransaksi editTransaksi  = new EditTransaksi();
        editTransaksi.getDriver().setUserEmail(driver.getUserEmail());
        editTransaksi.getDriver().setUserNama(driver.getUserNama());
        editTransaksi.getDriver().setUserLevel(driver.getUserLevel());
        int selectedRow = tableTransaksi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Mohon untuk memilih transaksi yang ingin di edit pada tabel");
        } else {
            Transaksi transaksi = getTransaksi(selectedRow);
            editTransaksi.setTransaksi(transaksi);
            editTransaksi.setVisible(true);
            loadTransaksi();
        }        
    }//GEN-LAST:event_editTransaksiButtonActionPerformed
    
    public void loadTransaksi() {
        deleteListInTable();
        driver.reloadData();
        String statusBayar;
        for (Transaksi p : driver.getListTransaksi()) {
            Penyewa penyewa = driver.getPenyewaById(p.getIdPenyewa());
            String date = dateFormat.format(p.getTanggalPengembalian());
            if (p.getStatusBayar() == 1) {
                statusBayar = "Sudah bayar";
            } else {
                statusBayar = "Belum bayar";
            }
            model.insertRow(model.getRowCount(), new Object[]{penyewa.getNama(), p.getNamaMobil(), p.getJumlahMobil(), p.getHarga(), date, p.getDenda(), statusBayar});   
        }
    }
    
    public Transaksi getTransaksi(int selectedRow) {
        Transaksi transaksi = new Transaksi();
        String namaPenyewa = "";
        String namaMobil = "";
        int jumlah = 0;
        int harga = 0;
        namaPenyewa = (String) tableTransaksi.getValueAt(selectedRow, 0);
        namaMobil = (String) tableTransaksi.getValueAt(selectedRow, 1);
        jumlah = (int) tableTransaksi.getValueAt(selectedRow, 2);
        harga = (int) tableTransaksi.getValueAt(selectedRow, 3);
        transaksi = driver.getTransaksi(namaPenyewa, namaMobil, jumlah, harga);
        return transaksi;
    }
    
    public void deleteListInTable() {
        model.setRowCount(0);
    }
    
    public Driver getDriver() {
        return driver;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteTransaksiButton;
    private javax.swing.JButton editTransaksiButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTransaksi;
    // End of variables declaration//GEN-END:variables
}
